---
# tasks file for db_users
- name: Create users
  community.postgresql.postgresql_user:
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    state: "{{ item.state }}"
  loop: "{{ db_users }}"

- name: Grant role to users
  community.postgresql.postgresql_membership:
    group: "{{ item.rolename }}"
    target_roles: "{{ item.username }}"
  loop: "{{ roles_map }}"
