#!.venv/bin/python3

import sys
from fabric import Connection

def Usage():
  print("Usage: check_la15 'ip list'")

def check_load(targets):
  print(targets.replace(",", " "))
  pass

def main(args=[]):
  if not args :
    Usage()
  else:
    check_load(args[0])

if __name__ == "__main__":
  main(sys.argv[1:])
